name: jeepway
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_database: ^11.3.6

  image_picker: ^1.1.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_map_marker_popup: ^8.0.1
  geolocator: ^14.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/jeepneyicon.png
